### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by magix12321** [AmshenShanu07/GRAB#1]
I tried to run this command:
$ python3 grab.py -u username

and then I got this, what do I do?

[+] getting profile ...Traceback (most recent call last):
  File "/home/magix/matrix/destruct/grab/GRAB/grab.py", line 16, in <module>
    ig = main(user=args["username"])
  File "/home/magix/matrix/destruct/grab/GRAB/.lib/api.py", line 60, in __init__
    self.get_profile()
  File "/home/magix/matrix/destruct/grab/GRAB/.lib/api.py", line 65, in get_profile
    soup = BeautifulSoup(profile.text, 'html.parser')
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/builder/_htmlparser.py", line 215, in feed
    parser.feed(markup)
  File "/usr/lib/python3.10/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.10/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
  File "/usr/lib/python3.10/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/builder/_htmlparser.py", line 160, in handle_decl
    self.soup.endData(Doctype)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/element.py", line 1054, in __getattr__
    return self.find(tag)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/element.py", line 1292, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/element.py", line 1313, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/element.py", line 1610, in __init__
    self.text = self._normalize_search_value(text)
  File "/home/magix/.local/lib/python3.10/site-packages/bs4/element.py", line 1615, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by AmshenShanu07** [comment]
Sorry, this code base is not updated and i am not interested in maintaining it
